# Generated by Django 3.2.5 on 2021-09-09 05:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.FloatField()),
                ('liveprojects', models.IntegerField()),
                ('eligibility', models.TextField()),
                ('trainingmode', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('courseintroduction', ckeditor.fields.RichTextField()),
                ('coursecontent', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Userquery',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
