# Generated by Django 3.2.5 on 2021-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourses',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
    ]
