# Generated by Django 3.2.5 on 2021-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0002_alter_addcourses_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourses',
            name='urlstructure',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
