# Generated by Django 3.2.5 on 2021-09-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0005_rename_cousrecategory_addcourses_coursecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcourses',
            old_name='urlstructure',
            new_name='slug',
        ),
    ]
