# Generated by Django 3.2.5 on 2021-09-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0008_rename_slug_addpage_pageslug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addpage',
            new_name='Addservice',
        ),
        migrations.RenameField(
            model_name='addservice',
            old_name='pagecontent',
            new_name='servicecontent',
        ),
        migrations.RenameField(
            model_name='addservice',
            old_name='pageimages',
            new_name='serviceimages',
        ),
        migrations.RenameField(
            model_name='addservice',
            old_name='pageslug',
            new_name='serviceslug',
        ),
        migrations.RenameField(
            model_name='addservice',
            old_name='pagetitle',
            new_name='servicetitle',
        ),
    ]
