# Generated by Django 3.2.5 on 2021-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0009_auto_20210911_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourses',
            name='coursecategory',
            field=models.CharField(choices=[('frontends', 'frontends'), ('programming', 'programming'), ('frameworks', 'frameworks'), ('databases', 'databases'), ('marketing', 'marketing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addcourses',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addservice',
            name='serviceslug',
            field=models.SlugField(max_length=500),
        ),
    ]
