# Generated by Django 3.2.5 on 2021-09-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0011_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='comment',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
