# Generated by Django 3.2.5 on 2021-09-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynetsoftwares', '0013_rename_comment_contactform_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('review_heading', models.CharField(max_length=50)),
                ('review_content', models.CharField(max_length=200)),
                ('student_images', models.ImageField(upload_to='studentimg')),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='msg',
            field=models.CharField(max_length=200),
        ),
    ]
